apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: asp-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: asp-web-app
        service: webapp
    spec:
      containers:
        - name: webapp
          image: vitorsouza97/aspwebapp:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: WebApiBaseAddress
              value: http://webapi
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: asp-web-app
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    service: webapp
