apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspwebapp
  labels:
    app: asp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: aspwebapp
  template:
    metadata:
      labels:
        app: asp-web
        service: aspwebapp
    spec:
      containers:
        - name: asp-net-razor-web-app
          image: vitorsouza97/aspwebapp:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: APIUrl
              value: http://webapi:5100
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: aspwebapp
  labels:
    app: asp-web
    service: aspwebapp
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    service: aspwebapp
