apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: asp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: asp-web
        service: webapi
    spec:
      containers:
        - name: asp-net-web-api
          image: vitorsouza97/aspwebapi:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5100
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5100
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: asp-web
    service: webapi
spec:
  ports:
    - port: 5100
      targetPort: 5100
      protocol: TCP
  selector:
    service: webapi
